module Decisions
  class BackDecisionTree < BaseDecisionTree
    # used to add custom methods to filter/query the data
    WRAPPER_CLASS = CustomWrapper
    CHECK_YOUR_ANSWERS = '/payments/steps/check_your_answers'.freeze
    CHANGE_YOUR_ANSWERS = 'change_your_answers'.freeze

    from(DecisionTree::NSM_CLAIM_DETAILS)
      .goto(edit: DecisionTree::OFFICE_CODE_SEARCH)
    from(DecisionTree::DATE_CLAIM_ASSESSED.sub(%r{^/}, ''))
      .goto(edit: DecisionTree::CLAIM_SEARCH.sub(%r{^/}, ''))
    from(DecisionTree::CLAIM_SEARCH.sub(%r{^/}, ''))
      .goto(edit: DecisionTree::CLAIM_TYPE)
    from(DecisionTree::NSM_CLAIMED_COSTS)
      .when(-> { nsm || (nsm_supplemental && multi_step_form_session.no_existing_ref?) })
      .goto(edit: DecisionTree::NSM_CLAIM_DETAILS)
      .when(-> { nsm_supplemental })
      .goto(edit: DecisionTree::DATE_CLAIM_ASSESSED)
    from(DecisionTree::NSM_ALLOWED_COSTS)
      .when(-> { nsm })
      .goto(edit: DecisionTree::NSM_CLAIMED_COSTS)
      .when(-> { nsm_supplemental })
      .goto(edit: DecisionTree::NSM_CLAIMED_COSTS)
      .when(-> { (nsm_appeal || nsm_amendment) && multi_step_form_session.no_existing_ref? })
      .goto(edit: DecisionTree::NSM_CLAIM_DETAILS)
      .when(-> { nsm_appeal || nsm_amendment })
      .goto(edit: DecisionTree::DATE_CLAIM_ASSESSED)
    from(CHECK_YOUR_ANSWERS.sub(%r{^/}, ''))
      .when(-> { ac || ac_appeal || ac_amendment })
      .goto(edit: DecisionTree::AC_ALLOWED_COSTS)
      .when(-> { nsm || nsm_supplemental || nsm_appeal || nsm_amendment })
      .goto(edit: DecisionTree::NSM_ALLOWED_COSTS)

    from(DecisionTree::AC_CLAIM_DETAILS.sub(%r{^/}, ''))
      .goto(edit: DecisionTree::COUNSEL_CODE_CONFIRM)
    from(DecisionTree::AC_CLAIMED_COSTS)
      .goto(edit: DecisionTree::AC_CLAIM_DETAILS)
    from(DecisionTree::AC_ALLOWED_COSTS)
      .when(-> { (ac_appeal || ac_amendment) && multi_step_form_session.no_existing_ref? })
      .goto(edit: DecisionTree::AC_CLAIM_DETAILS)
      .when(-> { ac_appeal || ac_amendment })
      .goto(edit: DecisionTree::DATE_CLAIM_ASSESSED)
      .when(-> { ac })
      .goto(edit: DecisionTree::AC_CLAIMED_COSTS)
    from(DecisionTree::OFFICE_CODE_SEARCH.sub(%r{^/}, ''))
      .when(-> { nsm })
      .goto(edit: DecisionTree::CLAIM_TYPE)
      .goto(edit: DecisionTree::CLAIM_SEARCH)
    from(DecisionTree::OFFICE_CODE_CONFIRM.sub(%r{^/}, ''))
      .goto(edit: DecisionTree::OFFICE_CODE_SEARCH)
    from(DecisionTree::COUNSEL_CODE_SEARCH.sub(%r{^/}, ''))
      .when(-> { multi_step_form_session.no_existing_ref? })
      .goto(edit: DecisionTree::OFFICE_CODE_CONFIRM)
      .goto(edit: DecisionTree::CLAIM_SEARCH.sub(%r{^/}, ''))
    from(DecisionTree::COUNSEL_CODE_CONFIRM.sub(%r{^/}, ''))
      .goto(edit: DecisionTree::COUNSEL_CODE_SEARCH)
    from(CHANGE_YOUR_ANSWERS)
      .goto(edit: CHECK_YOUR_ANSWERS)
  end
end
