ActiveModel::Type.register(:translated, LaaCrimeFormsCommon::Type::TranslatedObject)
ActiveModel::Type.register(:translated_array, LaaCrimeFormsCommon::Type::TranslatedObjectArray)
ActiveModel::Type.register(:time_period, LaaCrimeFormsCommon::Type::TimePeriod)
ActiveModel::Type.register(:gbp, LaaCrimeFormsCommon::Type::Gbp)
ActiveModel::Type.register(:fully_validatable_integer, LaaCrimeFormsCommon::Type::FullyValidatableInteger)
ActiveModel::Type.register(:fully_validatable_decimal, LaaCrimeFormsCommon::Type::FullyValidatableDecimal)
ActiveModel::Type.register(:multiparam_date, LaaCrimeFormsCommon::Type::MultiparamDate)
